networks:
  pundit: {}

volumes:
  prometheus_storage: {}
  grafana_storage: {}
  influxdb_data: {}

services:
  grafana:
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_USERS_DEFAULT_THEME: "light"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/snmp/snmp_pundit_exporter.json
    image: grafana/grafana:latest
    networks:
      pundit: null
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: unless-stopped
    volumes:
    -  grafana_storage:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro

  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:latest
    networks:
      pundit: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: unless-stopped
    volumes:
    - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=1y
    - --web.enable-admin-api
    - --web.enable-lifecycle
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      pundit: null
    ports:
    - published: 9090
      target: 9090
    restart: unless-stopped
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_storage:/prometheus

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:latest
    networks:
      pundit: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      pundit: null
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: unless-stopped
    volumes:
    - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mount the Telegraf configuration file
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount the Docker socket to collect Docker metrics
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'  # Expose Telegraf's StatsD port
    networks:
      pundit: null  # Connect the Telegraf container to the monitoring network
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpundit
    ports:
      - '8086:8086'  # Expose InfluxDB on port 8086
    volumes:
      - influxdb_data:/var/lib/influxdb  # Mount the InfluxDB data directory
    networks:
      pundit: null  # Connect the InfluxDB container to the monitoring network

  

