# global config
global:
  scrape_interval: 45s # Set the scrape interval to every 45 seconds. Default is every 1 minute.
  scrape_timeout: 30s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    origin_prometheus: pundit

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']


#### Windows Devices
#### Added windows devices with the following format
#### Windows Exporter can be installed from Ninja or https://github.com/prometheus-community/windows_exporter/releases/download/v0.29.2/windows_exporter-0.29.2-arm64.exe
#### msiexec /i <path-to-msi-file> --% ADDLOCAL=FirewallException

  #- job_name: 'DeviceName'
  #  scrape_interval: 1m
  #  metrics_path: /metrics
  #  static_configs:
  #  - targets: ['ipaddress:9200']

####SNMP Exporter
  - job_name: 'snmp'
    static_configs:
      - targets:
        #- ip address  # SNMP device.
        #- tcp://192.168.1.3:1161  # SNMP device using TCP transport and custom port.
    metrics_path: /snmp
    params:
      auth: [public_v1]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.

# Global exporter-level metrics
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['snmp_exporter:9116']      